LANG: 'russian'

package_downloader:
  download_packages:
    nltk_packages:
      - 'punkt'
      - 'stopwords'

data_loader:
  text_file_regex: '**/*.txt'

tokenizer:
  punctuation_regex: '[`“”Δδ•©.,;–\-+—»«><%:?!*=()\'\]\[\\/]+'

lemmatizer:
  name: 'pymorphy2'

filter:
  punctuation_regex: '[`“”Δδ•©.,;–\-+—»«><%:?!*=()\'\]\[\\/]+'

vocabulary_buider:
  max_size: 1000000
  max_doc_freq: 1
  min_count: 5
  pad_word: null

topic_model:
  name: 'LDA'
  num_topics: 20
  chunksize: 100
  passes: 10

visualizer:
  name: 'pyLDAvis'
